### PR TITLE
fix openocd patch

### PR DESCRIPTION
**Pull request by trabucayre**
Since commit af39ee607cd6ce6f3d809bd715892f2df1bf552a Digilent Nexys Video board is natively supported by openOCD, so `digilent-nexys_video.patch` is no more required and produces error in the patch step (as mentionned in PR #22).

This PR drop this patch and refresh `fpga-program.patch`

### CODE REVIEW

**Comment by mithro** [comment]
LGTM!

I'm unclear why there is no CI running on this repository? @PiotrZierhoffer - Any ideas?

**Comment by mithro** [comment]
@acomodi - Any idea why there is no CI on this repo?

**Comment by umarcor** [comment]
There were no pushes to the repo in 60 days and CI was automatically disabled. It's the default behaviour in GitHub. Some maintainer of this repo needs to reenable it in https://github.com/hdl/conda-prog/actions/workflows/build-packages.yml or just push some new commit to any branch.

**Comment by trabucayre** [comment]
Weird `openocd-osx` is okay but `openocd-linux` fails with:
```
  Cloning into '/home/runner/work/conda-prog/conda-prog/workdir/git-repos/openocd.git'...
  fatal: read error: Connection reset by peer
```
Tried to reproduce locally using `act` but this step pass.

**Comment by PiotrZierhoffer** [comment]
I didn't know about this 60-day thingy, thanks @umarcor 

@trabucayre it looks like a connection error, I'll restart the workflow

**Comment by trabucayre** [comment]
Thanks.
Seems okay now/ It's strange because it's not the first time this error appears: in #22 `openocd-linux` [fails]()https://github.com/hdl/conda-prog/pull/22/checks?check_run_id=3277761029) for the same reason

**Pull request merged**
